export const SPECIES_LIST = [
  { nombre_comun: 'Sapito Minero', nombre_cientifico: 'Dendrobates leucomelas' },
  { nombre_comun: 'Águila Arpía', nombre_cientifico: 'Harpia harpyja' },
  { nombre_comun: 'Gallito de las Rocas', nombre_cientifico: 'Rupicola rupicola' },
  { nombre_comun: 'Oso Palmero / Hormiguero Gigante', nombre_cientifico: 'Myrmecophaga tridactyla' },
  { nombre_comun: 'Tonina / Delfín Rosado', nombre_cientifico: 'Inia geoffrensis' },
  { nombre_comun: 'Azulejo', nombre_cientifico: 'Thraupis episcopus' },
  { nombre_comun: 'Cristofué', nombre_cientifico: 'Pitangus sulphuratus' },
  { nombre_comun: 'Zamuro', nombre_cientifico: 'Coragyps atratus' },
  { nombre_comun: 'Paloma común', nombre_cientifico: 'Columba livia' },
  { nombre_comun: 'Tortolita', nombre_cientifico: 'Columbina talpacoti' },
  { nombre_comun: 'Turpial', nombre_cientifico: 'Icterus icterus' },
  { nombre_comun: 'Paraulata llanera', nombre_cientifico: 'Mimus gilvus' },
  { nombre_comun: 'Cucarachero', nombre_cientifico: 'Troglodytes aedon' },
  { nombre_comun: 'Cotorra cara sucia', nombre_cientifico: 'Eupsittula pertinax' },
  { nombre_comun: 'Loro real', nombre_cientifico: 'Amazona ochrocephala' },
  { nombre_comun: 'Guacamaya azul y amarilla', nombre_cientifico: 'Ara ararauna' },
  { nombre_comun: 'Guacamaya roja', nombre_cientifico: 'Ara chloropterus' },
  { nombre_comun: 'Carpintero habado', nombre_cientifico: 'Melanerpes rubricapillus' },
  { nombre_comun: 'Tucusito', nombre_cientifico: 'Amazilia fimbriata' },
  { nombre_comun: 'Garza blanca', nombre_cientifico: 'Ardea alba' },
  { nombre_comun: 'Garcita reznera', nombre_cientifico: 'Bubulcus ibis' },
  { nombre_comun: 'Garza mora', nombre_cientifico: 'Ardea cocoi' },
  { nombre_comun: 'Alcaraván', nombre_cientifico: 'Vanellus chilensis' },
  { nombre_comun: 'Gavilán habado', nombre_cientifico: 'Rupornis magnirostris' },
  { nombre_comun: 'Arrendajo', nombre_cientifico: 'Cacicus cela' },
  { nombre_comun: 'Tordito', nombre_cientifico: 'Molothrus bonariensis' },
  { nombre_comun: 'Golondrina urbana', nombre_cientifico: 'Progne chalybea' },
  { nombre_comun: 'Tijereta', nombre_cientifico: 'Tyrannus savana' },
  { nombre_comun: 'Querrequerre', nombre_cientifico: 'Cyanocorax yncas' },
  { nombre_comun: 'Martín pescador amazónico', nombre_cientifico: 'Chloroceryle amazona' },
  { nombre_comun: 'Perro doméstico', nombre_cientifico: 'Canis lupus familiaris' },
  { nombre_comun: 'Gato doméstico', nombre_cientifico: 'Felis catus' },
  { nombre_comun: 'Rabipelado', nombre_cientifico: 'Didelphis marsupialis' },
  { nombre_comun: 'Rata de alcantarilla', nombre_cientifico: 'Rattus norvegicus' },
  { nombre_comun: 'Ratón de casa', nombre_cientifico: 'Mus musculus' },
  { nombre_comun: 'Ardilla', nombre_cientifico: 'Sciurus granatensis' },
  { nombre_comun: 'Murciélago frutero', nombre_cientifico: 'Artibeus lituratus' },
  { nombre_comun: 'Murciélago insectívoro', nombre_cientifico: 'Molossus molossus' },
  { nombre_comun: 'Pereza de tres dedos', nombre_cientifico: 'Bradypus tridactylus' },
  { nombre_comun: 'Mono capuchino', nombre_cientifico: 'Cebus olivaceus' },
  { nombre_comun: 'Mono araguato', nombre_cientifico: 'Alouatta seniculus' },
  { nombre_comun: 'Acure', nombre_cientifico: 'Dasyprocta leporina' },
  { nombre_comun: 'Chigüire', nombre_cientifico: 'Hydrochoerus hydrochaeris' },
  { nombre_comun: 'Cachicamo', nombre_cientifico: 'Dasypus novemcinctus' },
  { nombre_comun: 'Tuqueque', nombre_cientifico: 'Hemidactylus mabouia' },
  { nombre_comun: 'Iguana verde', nombre_cientifico: 'Iguana iguana' },
  { nombre_comun: 'Mato de agua', nombre_cientifico: 'Tupinambis teguixin' },
  { nombre_comun: 'Morrocoy sabanero', nombre_cientifico: 'Chelonoidis carbonaria' },
  { nombre_comun: 'Babo', nombre_cientifico: 'Caiman crocodilus' },
  { nombre_comun: 'Tragavenado', nombre_cientifico: 'Boa constrictor' },
  { nombre_comun: 'Mapanare', nombre_cientifico: 'Bothrops atrox' },
  { nombre_comun: 'Falsa coral', nombre_cientifico: 'Oxyrhopus petolarius' },
  { nombre_comun: 'Sapo común', nombre_cientifico: 'Rhinella marina' },
  { nombre_comun: 'Ranita platanera', nombre_cientifico: 'Boana crepitans' },
  { nombre_comun: 'Zancudo patas blancas', nombre_cientifico: 'Aedes aegypti' },
  { nombre_comun: 'Chiripa', nombre_cientifico: 'Blattella germanica' },
  { nombre_comun: 'Cucaracha americana', nombre_cientifico: 'Periplaneta americana' },
  { nombre_comun: 'Mosca doméstica', nombre_cientifico: 'Musca domestica' },
  { nombre_comun: 'Bachaco rojo', nombre_cientifico: 'Atta sexdens' },
  { nombre_comun: 'Hormiga loca', nombre_cientifico: 'Nylanderia fulva' },
  { nombre_comun: 'Comején', nombre_cientifico: 'Nasutitermes corniger' },
  { nombre_comun: 'Avispa papelera', nombre_cientifico: 'Polistes versicolor' },
  { nombre_comun: 'Abeja africanizada', nombre_cientifico: 'Apis mellifera' },
  { nombre_comun: 'Mariposa monarca', nombre_cientifico: 'Danaus plexippus' },
  { nombre_comun: 'Mariposa azul', nombre_cientifico: 'Morpho peleides' },
  { nombre_comun: 'Chipo', nombre_cientifico: 'Rhodnius prolixus' },
  { nombre_comun: 'Araña patona', nombre_cientifico: 'Pholcus phalangioides' },
  { nombre_comun: 'Alacrán', nombre_cientifico: 'Tityus discrepans' },
  { nombre_comun: 'Caracol gigante africano', nombre_cientifico: 'Achatina fulica' },
  { nombre_comun: 'Ciempiés', nombre_cientifico: 'Scolopendra gigantea' },
  { nombre_comun: 'Mango', nombre_cientifico: 'Mangifera indica' },
  { nombre_comun: 'Apamate', nombre_cientifico: 'Tabebuia rosea' },
  { nombre_comun: 'Aragüaney', nombre_cientifico: 'Handroanthus chrysanthus' },
  { nombre_comun: 'Ceiba', nombre_cientifico: 'Ceiba pentandra' },
  { nombre_comun: 'Caoba', nombre_cientifico: 'Swietenia macrophylla' },
  { nombre_comun: 'Caro Caro', nombre_cientifico: 'Enterolobium cyclocarpum' },
  { nombre_comun: 'Merey', nombre_cientifico: 'Anacardium occidentale' },
  { nombre_comun: 'Mamón', nombre_cientifico: 'Melicoccus bijugatus' },
  { nombre_comun: 'Guayaba', nombre_cientifico: 'Psidium guajava' },
  { nombre_comun: 'Pumalaca', nombre_cientifico: 'Syzygium malaccense' },
  { nombre_comun: 'Jobo', nombre_cientifico: 'Spondias mombin' },
  { nombre_comun: 'Samán', nombre_cientifico: 'Samanea saman' },
  { nombre_comun: 'Tamarindo', nombre_cientifico: 'Tamarindus indica' },
  { nombre_comun: 'Limón', nombre_cientifico: 'Citrus limon' },
  { nombre_comun: 'Aguacate', nombre_cientifico: 'Persea americana' },
  { nombre_comun: 'Pumarosa', nombre_cientifico: 'Syzygium jambos' },
  { nombre_comun: 'Níspero', nombre_cientifico: 'Manilkara zapota' },
  { nombre_comun: 'Cují', nombre_cientifico: 'Prosopis juliflora' },
  { nombre_comun: 'Jabillo', nombre_cientifico: 'Hura crepitans' },
  { nombre_comun: 'Ixora', nombre_cientifico: 'Ixora coccinea' },
  { nombre_comun: 'Trinitaria', nombre_cientifico: 'Bougainvillea glabra' },
  { nombre_comun: 'Cayena', nombre_cientifico: 'Hibiscus rosa-sinensis' },
  { nombre_comun: 'Almendrón', nombre_cientifico: 'Terminalia catappa' },
  { nombre_comun: 'Palma moriche', nombre_cientifico: 'Mauritia flexuosa' },
  { nombre_comun: 'Chaguaramo', nombre_cientifico: 'Roystonea oleracea' },
  { nombre_comun: 'Malojillo', nombre_cientifico: 'Cymbopogon citratus' },
  { nombre_comun: 'Orégano orejón', nombre_cientifico: 'Plectranthus amboinicus' },
  { nombre_comun: 'Sábila', nombre_cientifico: 'Aloe vera' },
  { nombre_comun: 'Llantén', nombre_cientifico: 'Plantago major' },
  { nombre_comun: 'Onoto', nombre_cientifico: 'Bixa orellana' }
];